### ISSUE TITLE
multiple theme options?

### ISSUE THREAD

**Issue by Falieson** [mAAdhaTTah/babel-plugin-prismjs#27]
thanks for making this plugin- very nice!
I provide a few different theme-ing modes to my users and I'm wondering how you recommend to give a few themes for them to choose from?
changing the theme config option to an array would be the easiest way probably, instead I'm doing the manual import way.
Thanks!

**Comment by mAAdhaTTah** [comment]
That would have to be a manual setup, depending on your build process & setup. In a past implementation, I swapped out the `href` on the link tag to point to the different themes. The plugin isn't going to help you for that though.

Feel free to ask follow-up questions, but closing this because there isn't anything actionable here.
